# Doc: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
image: jfgarcia268/sfdx_vlocity_java:v1.0
pipelines:
  branches:
    dev:
      - step:
          name: SF Deploy
          script:
            - echo ${SIT_CI_SFDX_URL} > env.sfdx
            - sfdx force:auth:sfdxurl:store -d -a ${SIT_CI_SFDX_URL} -f env.sfdx
            - sfdx force:source:deploy --sourcepath salesforce_sfdx --targetusername ${SIT_CI_SFDX_URL} --verbose
      - step:
          name: Vlocity Deploy
          script:
           - echo ${SIT_CI_SFDX_URL} > env.sfdx
           - sfdx force:auth:sfdxurl:store -d -a ${SIT_CI_SFDX_URL} -f env.sfdx
           - vlocity -sfdx.username ${SIT_CI_SFDX_URL} -job jobs/deploy.yaml packDeploy --verbose true --simpleLogging true 
  custom:
    PMDRun:
      - step:
          name: PMD Run
          script:
            - ./PMD/bin/run.sh pmd -no-cache -d "./salesforce_sfdx/main/default" -R "./PMD/Rules/quickstart.xml" -f csv > "./pmdresults.csv" || true
            - ls -la  
            - echo "PMD Results" | mail -v -s "PMD Results" jgonzalez@vlocity.com -a From:jgonzalez@vlocity.com -A pmdresults.csv
    prodDeploy:
      - step:
          name: SF Deploy
          script:
            - echo ${MASTER_PROD_SFDX_URL} > env.sfdx
            - sfdx force:auth:sfdxurl:store -d -a ${MASTER_PROD_SFDX_URL} -f env.sfdx
            - sfdx force:source:deploy --sourcepath salesforce_sfdx --targetusername ${MASTER_PROD_SFDX_URL} --verbose
      - step:
          name: Vlocity Deploy
          script:
           - echo ${MASTER_PROD_SFDX_URL} > env.sfdx
           - sfdx force:auth:sfdxurl:store -d -a ${MASTER_PROD_SFDX_URL} -f env.sfdx
           - vlocity -sfdx.username ${MASTER_PROD_SFDX_URL} -job jobs/deploy.yaml packDeploy --verbose true --simpleLogging true
    UATDeploy:
      - step:
          name: SF Deploy
          script:
            - echo ${UAT_SFDX_URL} > env.sfdx
            - sfdx force:auth:sfdxurl:store -d -a ${UAT_SFDX_URL} -f env.sfdx
            - sfdx force:source:deploy --sourcepath salesforce_sfdx --targetusername ${UAT_SFDX_URL} --verbose
      - step:
          name: Vlocity Deploy
          script:
           - echo ${UAT_SFDX_URL} > env.sfdx
           - sfdx force:auth:sfdxurl:store -d -a ${UAT_SFDX_URL} -f env.sfdx
           - vlocity -sfdx.username ${UAT_SFDX_URL} -job jobs/deploy.yaml packDeploy --verbose true --simpleLogging true



